apiVersion: batch/v1
kind: Job
metadata:
  name: orion-worker-connectivity-check
  namespace: orion-worker
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: orion-worker-connectivity-check
    spec:
      restartPolicy: Never

      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "orion-build"
          effect: "NoSchedule"


      containers:
        - name: check
          image: curlimages/curl:8.6.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -lc
            - |
              set -euo pipefail
              echo "== DNS check =="
              getent hosts orion.gitmono.com
              getent hosts git.gitmono.com

              echo "== HTTPS check (Mono) =="
              curl -fsSIL --max-time 10 https://git.gitmono.com

              echo "== HTTPS check (Orion host, via WS endpoint URL but over HTTPS) =="
              curl -fsSIL --max-time 10 https://orion.gitmono.com

              echo "== WebSocket endpoint reachability (TLS handshake + HTTP upgrade attempt) =="
              # curl can't fully validate WS app logic, but can at least reach the endpoint and attempt upgrade.
              curl -vk --http1.1 --max-time 10 \
                -H "Connection: Upgrade" \
                -H "Upgrade: websocket" \
                -H "Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==" \
                -H "Sec-WebSocket-Version: 13" \
                https://orion.gitmono.com/ws \
                -o /dev/null

              echo "ALL_CHECKS_PASSED"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

