apiVersion: batch/v1
kind: Job
metadata:
  name: orion-task-e2e-trigger
  namespace: orion-worker
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: orion-task-e2e-trigger
    spec:
      restartPolicy: Never
      tolerations:
        - key: dedicated
          operator: Equal
          value: orion-build
          effect: NoSchedule
      containers:
        - name: trigger
          image: curlimages/curl:8.6.0
          env:
            - name: ORION_API_BASE
              value: "https://orion.gitmono.com"
            - name: ORION_TASK_CL
              value: "18410001"
            - name: ORION_TASK_CL_LINK
              value: "https://example.invalid/cl/18410001"
            - name: ORION_REPO
              value: "mega"
            - name: ORION_TARGET
              value: "//:noop"
            - name: ORION_POLL_SECONDS
              value: "300"
          command:
            - /bin/sh
            - -c
            - |-
                set -ex
                echo "== Create task =="
                payload=$(cat <<'JSON'
                {
                  "repo": "REPO_PLACEHOLDER",
                  "cl_link": "CL_LINK_PLACEHOLDER",
                  "cl": CL_PLACEHOLDER,
                  "builds": [
                    { "target": "TARGET_PLACEHOLDER", "args": null, "changes": [] }
                  ]
                }
                JSON
                )
                payload=$(echo "$payload" | sed -e "s/REPO_PLACEHOLDER/${ORION_REPO}/g" \
                                                -e "s|CL_LINK_PLACEHOLDER|${ORION_TASK_CL_LINK}|g" \
                                                -e "s/CL_PLACEHOLDER/${ORION_TASK_CL}/g" \
                                                -e "s|TARGET_PLACEHOLDER|${ORION_TARGET}|g")

                resp=$(curl -fsS -X POST "${ORION_API_BASE}/task" -H 'content-type: application/json' --data "$payload")
                echo "$resp"

                task_id=$(echo "$resp" | sed -n 's/.*"task_id"[[:space:]]*:[[:space:]]*"\([^\"]*\)".*/\1/p')
                [ -z "$task_id" ] && { echo "parse task_id fail"; exit 2; }
                echo "task_id=$task_id"

                deadline=$(( $(date +%s) + ORION_POLL_SECONDS ))
                while :; do
                  now=$(date +%s)
                  [ "$now" -ge "$deadline" ] && { echo "timeout" >&2; exit 3; }

                  all_tasks=$(curl -fsS "${ORION_API_BASE}/tasks/${ORION_TASK_CL}")
                  
                  # Use sed + grep to reliably extract the JSON object for the current task_id
                  current_task=$(echo "$all_tasks" | sed 's/},{/}\n{/g' | grep "\"task_id\":\"$task_id\"" || true)

                  if [ -z "$current_task" ]; then
                    echo "poll: task_not_visible_yet"
                    sleep 3
                    continue
                  fi

                  completed=$(echo "$current_task" | grep -c '"status":"Completed"' || true)
                  building=$(echo "$current_task" | grep -c '"status":"Building"' || true)
                  failed=$(echo "$current_task" | grep -c '"status":"Failed"' || true)
                  interrupted=$(echo "$current_task" | grep -c '"status":"Interrupted"' || true)

                  echo "poll(current_task): completed=$completed building=$building failed=$failed interrupted=$interrupted"
                  [ "$completed" -gt 0 ] && { echo "TASK_E2E_PASSED"; exit 0; }
                  { [ "$failed" -gt 0 ] || [ "$interrupted" -gt 0 ]; } && {
                    echo "TASK_E2E_FAILED" >&2
                    echo "$current_task" | cat >&2
                    exit 4
                  }

                  sleep 5
                done
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
