apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: orion-worker
  namespace: orion-worker
  labels:
    app: orion-worker
spec:
  selector:
    matchLabels:
      app: orion-worker
  template:
    metadata:
      labels:
        app: orion-worker
    spec:
      serviceAccountName: orion-worker-sa
      terminationGracePeriodSeconds: 300

      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "orion-build"
          effect: "NoSchedule"

      nodeSelector:
        nodepool: build-default

      containers:
        - name: orion-worker
          image: public.ecr.aws/m8q5m4u3/mega:orion-client-0.1.0-pre-release-amd64
          # Start scorpio first, print its startup logs, then exec orion
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              # Force localhost to resolve to IPv4 to avoid IPv6 connection issues
              echo "127.0.0.1 localhost" >> /etc/hosts

              echo "Generating scorpio config via envsubst..."
              envsubst < /etc/scorpio/scorpio.toml.template > /tmp/scorpio.toml

              echo "Attempting to start scorpio in background..."
              # Run scorpio with config, listening on default 0.0.0.0:2725
              /app/bin/scorpio --config-path /tmp/scorpio.toml > /tmp/scorpio.log 2>&1 &
              sleep 2
              echo "--- Scorpio Log Start ---"
              cat /tmp/scorpio.log || true
              echo "--- Scorpio Log End ---"
              exec orion

          envFrom:
            - configMapRef:
                name: orion-worker-config
            - secretRef:
                name: orion-worker-secret
                optional: true

          env:
            - name: ORION_WORKER_START_SCORPIO
              value: "true"
            - name: SCORPIO_STORE_PATH
              value: "/data/scorpio/store"
            - name: SCORPIO_WORKSPACE
              value: "/workspace/mount"
            - name: BUCK_PROJECT_ROOT
              value: "/workspace"
            - name: BUILD_TMP
              value: "/tmp/orion-builds"

            - name: SCORPIO_GIT_AUTHOR
              value: "orion"
            - name: SCORPIO_GIT_EMAIL
              value: "orion@local"

            - name: SCORPIO_DICFUSE_READABLE
              value: "true"
            - name: SCORPIO_LOAD_DIR_DEPTH
              value: "2"
            - name: SCORPIO_FETCH_FILE_THREAD
              value: "8"
            - name: SCORPIO_DICFUSE_IMPORT_CONCURRENCY
              value: "8"
            - name: SCORPIO_DICFUSE_DIR_SYNC_TTL_SECS
              value: "60"
            - name: SCORPIO_DICFUSE_STAT_MODE
              value: "fast"
            - name: SCORPIO_DICFUSE_OPEN_BUFF_MAX_BYTES
              value: "134217728"
            - name: SCORPIO_DICFUSE_OPEN_BUFF_MAX_FILES
              value: "2048"

            - name: ANTARES_LOAD_DIR_DEPTH
              value: "2"
            - name: ANTARES_DICFUSE_STAT_MODE
              value: "fast"
            - name: ANTARES_DICFUSE_OPEN_BUFF_MAX_BYTES
              value: "134217728"
            - name: ANTARES_DICFUSE_OPEN_BUFF_MAX_FILES
              value: "2048"
            - name: ANTARES_DICFUSE_DIR_SYNC_TTL_SECS
              value: "60"
            - name: ANTARES_UPPER_ROOT
              value: "/data/scorpio/antares/upper"
            - name: ANTARES_CL_ROOT
              value: "/data/scorpio/antares/cl"
            - name: ANTARES_MOUNT_ROOT
              value: "/workspace/mount"
            - name: ANTARES_STATE_FILE
              value: "/data/scorpio/antares/state.json"

          securityContext:
            privileged: true

          resources:
            requests:
              cpu: "6"
              memory: "24Gi"
            limits:
              cpu: "8"
              memory: "30Gi"

          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-lc", "sleep 10"]

          volumeMounts:
            - name: orion-data-cache
              mountPath: /data
            - name: orion-workspace-cache
              mountPath: /workspace
            - name: scorpio-config
              mountPath: /etc/scorpio/scorpio.toml.template
              subPath: scorpio.toml.template

      volumes:
        - name: orion-data-cache
          hostPath:
            path: /var/lib/orion/data
            type: DirectoryOrCreate
        - name: orion-workspace-cache
          hostPath:
            path: /var/lib/orion/workspace
            type: DirectoryOrCreate
        - name: scorpio-config
          configMap:
            name: scorpio-config
